language: python
python:
  - "3.5"  # 3.5 development branch
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

cache:
  directories:
  - $HOME/.cache/pip

script:
  - python test.py